name: Deploy static content to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering from Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install  # Replace with your package manager and build commands
          npm run build  # Replace with your build script if applicable

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with your build output directory

      # Optional: Add additional steps as needed (e.g., notifications)

